### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by vimal7** [sideeffects/GameDevelopmentToolset#3]
First of all Thanks for this amazing plugins.

I have a quick question? 
Is there any way we can write out the RBD sim before and use the cache to create these keyframes ??
or possibility to work with cached out sims ??
Thanks
Vimal

**Comment by Shadowist** [comment]
Hey Vimal!

Not at the moment. I've been working with simulations that haven't required caches, but that's something I'll check on when I get into the office in the morning. I just added a commit to the [Destruction](https://github.com/sideeffects/GameDevelopmentShelf/tree/Destruction) branch that gets it most of the way there. However, it appears to be one frame off due to how the creation frame is handled when caching simulations. Should be an easy fix.

Thanks!

-Steve

**Comment by Shadowist** [comment]
Hah. The tool was actually working as expected. Apparently there's a minor discrepancy between Houdini's cached and non-cached sim when the creation frame is set to $RFSTART-1. I'll need to look into refining that workflow. However, since this particular issue is resolved, I'm going close it.

The [main branch](https://github.com/sideeffects/GameDevelopmentShelf/tree/Houdini15.0) has been merged with the fix.

Thanks Vimal!

-Steve
