### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jimwinquist** [sideeffects/GameDevelopmentToolset#64]
Is there a LICENSE.txt that can be included with this repository? 

If these tools are all open source, it would be great to be able to use them in a studio development setting. Or if these are included as part of the Houdini licensing agreement, it would be great to know how the licensing model works.

**Comment by jnlopar** [comment]
+1 this is also important if we want to contribute from the community and send any pull requests. I need to clear any patches for OSS I send with my organization, which includes needing to know the license as well as any CLA requirements.

**Comment by dpernuit** [comment]
Hi,

The repo has been updated with a LICENSE file.

 Copyright (c) 2017
	Side Effects Software Inc.  All rights reserved.

 Redistribution and use of in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.

 2. The name of Side Effects Software may not be used to endorse or
    promote products derived from this software without specific prior
    written permission.

 THIS SOFTWARE IS PROVIDED BY SIDE EFFECTS SOFTWARE `AS IS' AND ANY EXPRESS
 OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
 NO EVENT SHALL SIDE EFFECTS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
