### ISSUE TITLE
MapBox - cannot see and download any data on Linux Centos 7.2 + H17

### ISSUE THREAD

**Issue by djczaps** [sideeffects/GameDevelopmentToolset#94]
Hi

I've tried to test mapBox node on Linux Centos 7.2 environment with Houdini H17.0.352 and H17.0.389.
No matter what I do ( even tried to create custom token on MapBox) after pasting my public API key the map viewer doesn't show anything. There is only a blank window download ( blind data ) also seems to do nothing. No errors pops in except of warning in general node when created. However this error is generated due to there is no connection between anything just yet.

any ideas how to make it work on Linux ? It maybe the browser IN/OUT connection issue ?

cheers

djczaps

**Comment by curadotd** [comment]
I am having the same issue with Fedora 28, also tried the new daily build 17.0.390, also get an error on the sop:

Error | Invalid source /obj/geo1/sop_mapbox1/convert_to_geo/repeat_end1Error: Failure to cook template geometry..

and when clicking the refresh button I get this error:

Traceback (most recent call last):
  File "opdef:/gamedev::Sop/sop_mapbox?PythonModule", line 35, in url_changed
IndexError: list index out of range

with 1.60 or master checked out for the GameDevelopmentToolset.

If any one finds anything that would be awesome, thank you in adavance.

**Comment by jonahtobias** [comment]
I can report the same issue with Mac OS

**Comment by gitToad** [comment]
yep same on Mac OS 10.13.6 High Sierra, H17.0.352
Same with GD production toolset 1.72 and daily 1.80
White map dialog (no map), and pressing download button also doesnt seem to do anything.

Identical behavior with default free mapbox API key and custom one with all (well at least the Read and List, not the Write) services enabled.

After pressing the "download" button on a white map dialog, the Mapbox sop node reports:
![image](https://user-images.githubusercontent.com/503035/48754038-24da8780-ec45-11e8-874e-92cdaca61797.png)

Further experimentation:
I manually copied lat lon zoom values from Indie-pixel's tutorial
https://lesterbanks.com/2018/11/introduction-houdini-mapbox-node/#comment-194784
Lat=36.2345 Lon=-112.467 Zoom=11

clicked refresh and got this dialog:
Error running Python code to access the help manager:
![image](https://user-images.githubusercontent.com/503035/48754884-2b1e3300-ec48-11e8-9854-8fb0ffc3946e.png)

**Comment by brunokindt** [comment]
Opening mapbox with "Look Up" or "Refresh" gives the following error (visible when starting houdini from a terminal) on Fedora release 28

`Qt Error: Uncaught ReferenceError: mapboxgl is not defined`

It seems Mapbox GL JS does not like QWebEngineView on Linux. Updating mapbox_map.html did work, https://gist.github.com/brunokindt/d0c42ff680bd4cf1d7ce98c34270c421 (not tested on Mac OS or Windows ).

- mapbox_map.html (otls/sop_mapbox.hda/gamedev_8_8Sop_1sop__mapbox/mapbox__map.html) does work in firefox and google chrome, not in QWebEngineView.
- Loading mapbox javascript and css with over https did not work, http version did load.
- Mapbox GL JS did not work in QWebEngineView ( mapboxgl is not available after loading the required javascript ).
- mapbox.js did work ( none GL version of mapbox ) https://www.mapbox.com/mapbox.js/api/v3.1.1/
- mapbox.js also required loading over http instead of https
- The 'L' is not available after loading the mapbox.js, using an interval to check if 'L' is available did work.
- Update location.hash after creating the map calls url_changed in PythonModule which closes the window. ( view PythonModule.patch in above git url for possible solution )

Unrelated to linux issue:
"Download Path Color" defaults to "$HIP/maps/terrain_color.png" but the Mapbox API will always return a JPEG.

details:

GameDevelopmentToolset Development branch ( commit 09bbc5f of Fri Nov 23 14:14:02 2018 -0800 )
Houdini FX Version 17.0.352
Operating System: Fedora release 28 (Twenty Eight)

**Comment by lkruel** [comment]
Awesome! Thank you so much for doing this! 
I'm merging in the HTML. also fixed the jpg/png thing
